#!/bin/sh

link="$(curl https://github.com/GloriousEggroll/proton-ge-custom/releases/latest 2>/dev/null | grep -o '"http.*"')"
tag="$(echo "$link" | grep -o '[0-9].*[0-9]-GE-[0-9]-*')"

# Project uses two different tagging schemes. Match for second if first is not matched.
if [ -z "${tag}" ] ; then
    tag="$(echo "$link" | grep -o 'GE-Proton[0-9]-[0-9]*[0-9]')"
    tarball="${tag}"
else
    tarball="Proton-${tag}"
fi

echo "Downloading from ${link}"

install() {
    wget https://github.com/GloriousEggroll/proton-ge-custom/releases/download/"${tag}"/"${tarball}".tar.gz --show-progress -qO - | tee >(tar -xzC "${HOME}"/.steam/root/compatibilitytools.d/) >(sha512sum -)
}

checksum() {
    valid=$(wget https://github.com/GloriousEggroll/proton-ge-custom/releases/download/"${tag}"/"${tarball}".sha512sum -qO - | cut -f 1 | sha512sum)
    tarhash=$(wget https://github.com/GloriousEggroll/proton-ge-custom/releases/download/"${tag}"/"${tarball}".tar.gz -qO - | sha512sum -)
    if [ "${tarhash}" = "${valid}" ] ; then
        echo "File checksum MATCHED!"
    else
        echo "Checksum MISMATCH! Please verify file integrity."
    fi
}

printf "Installing Proton %s to ~/.steam/root/compatibilitytools.d/\n" "$tag"

install &&
echo "Done!"
