#!/bin/sh

set -eu

scripts_dir="~/code/dc/scripts"
cd "${scripts_dir}"

cmd=$1
path_cmd=$(command -v ${cmd})
script_inode=$(ls -i ${cmd} | cut -d' ' -f1)
path_inode=$(ls -i ${path_cmd} | cut -d' ' -f1)

if [ "${script_inode}" = "${path_inode}" ] ; then
    echo "Script in PATH already matches file in git repo. Nothing to do."
    exit
fi

git restore "${cmd}" &&
    echo "Restoring ${cmd} from local git HEAD."
cat "${cmd}" > "${path_cmd}" &&
ln "${path_cmd}" "${cmd}" &&
