#!/bin/sh

channel="$1"
if [ -z "$2" ] ; then
    quality="best"
else
    case $2 in
        [7]|[7][2][0]* )
            quality="best[height<=720]"
            ;;
        [4]|[4][8][0]* )
            quality="best[height<=480]"
            ;;
        [3]|[3][6][0]* )
            quality="best[height<=360]"
            ;;
    esac
fi

case $1 in
    [k][o][n]|[k][q] )
        channel="konquesting"
        ;;
    [z][a][r][i][c]|[z][z] )
        channel="zhakaron"
        ;;
    [r][o][b]|[r][w][x] )
        channel="rwxrob"
        ;;
esac

start_mpv() {
    mpv --ytdl-format="$quality" https://twitch.tv/"$channel" > /dev/null 2>&1 &
    return
}

start_mpv 

if [ "$?" = 2 ] ; then
    echo Twitch channel "$1" is offline or not found.
    
fi


