#!/bin/sh

vidnum=$1
playlist_url=$2
while [ true ] ; do
    if [ ${vidnum} -gt 0 ] 2>/dev/null ; then
        break
    else
        printf "Enter number in video playlist: "
        read vidnum
    fi
done

mpv --ytdl-raw-options="compat-options=youtube-dl,playlist-start=${vidnum}" "${playlist_url}"
